### ISSUE TITLE
This only works for image...

### ISSUE THREAD

**Issue by faurelia** [samayo/bulletproof#101]
This looks simple and easy to use but it only works on images. So of you want to try `csv`, `xlsx`, it won't work unless maybe you can change `acceptedMimes` which is protected so you can only do that if you make your own inheriting the `Image` class.

**Comment by samayo** [comment]
Yes, but it seems like you are answering a question, but which question? 

Did you mean to create an issue? Because it is clearly mentioned in the readme, that this library is for uploading images only

**Comment by samayo** [comment]
Closing issue, feel free to open if you have more questions
