### ISSUE TITLE
iphone upload

### ISSUE THREAD

**Issue by Vetru** [samayo/bulletproof#105]
Hello, i tried so many codes but it didn't upload photo from iphone,

i search for the solution and i found that iphone is submitting image as rotate but in bulletproof not work.

is there any answer for this?

anyone?

best regards

**Comment by twistedpixel** [comment]
I don’t understand. Are you saying you cannot upload from iPhone at all? Or it uploads the image rotated at 90 degrees?

**Comment by samayo** [comment]
Sorry for the delay, but this question has been asked here before. See issue #39 and OP also made a post in reddit asking for help, here is the link. https://www.reddit.com/r/PHP/comments/3ixl6i/strange_image_rotation_when_uploading_directly/cuklna0/

closing it for now
