### ISSUE TITLE
How to delete existing (old) file while update?

### ISSUE THREAD

**Issue by jodyshop** [samayo/bulletproof#106]
Hi,
I have implemented the (bulletproof) uploader in my script. But when I try to update my records by changing the DB table row for example:

Update old game image with a new game image (I am using a rename method)! I find that the image uploaded (and renamed) but the old image still exists in the thumbs folder.

Here is my code:

`$newthumb=false;
if($continue){
	$bulletProof = new ImageUploader\BulletProof;

	try{	
	if($_FILES && $_FILES['avaimage']['name']){
	$name3=strtolower($game_name);
	$name3=str_replace(' ', '-',$name3);
	$thumbnail=$name3.'-'.generateRandomString();
	$pic1=$bulletProof->uploadDir("../thumbs")->shrink(array("height"=>200, "width"=>200))->upload($_FILES['avaimage'],$thumbnail);
	if($pic1){
	$thumb=$pic1;
	}
	}
	}catch(\ImageUploader\ImageUploaderException $e){
	 $error=$e->getMessage();
	$continue=false;
	}
}`

I used to delete the old files while updating to prevent exhausted disk space and keep my site clean and easy to manage, but this way if I changed the game image 10 times, I'll get 10 diff images and so on, This is a bad thing.

![dub_img](https://user-images.githubusercontent.com/28163331/59559459-f3be0c00-9007-11e9-9701-055235c1ef42.png)

Any help will be appriciated.
Thanks

**Comment by twistedpixel** [comment]
I don’t really understand the issue. If you need to keep track of randomly named uploads (images, in your case) you need to store the name(s) in database records. Then you’d pull those records and delete the old images once you confirm the new image is uploaded successfully.

You’d probably get more help posting your question on StackOverflow. GitHub issues is really for reporting problems with the project (which this is not: it is an implementation problem).

**Comment by jodyshop** [comment]
Okay, I have already posted in StackOverflow, To be more clear, the issue is that there is no option to delete old uploaded files (images) for the same post.

As I mentioned, I want to **delete the thumbnail if exists**... Because when I update the post (a game in my case) and choose a new image, the old one remains in the thumbs folder (of course changed in the DB with the new one)!

In my old framework I used to use this class:

```
/**
	 * delete the tumbnails if exists
	 * @var string folder name
	 * @var string name of the file
	 * @return nothing
	 * @access public
	 */
	function deleteThumbnails($folder, $oldName) {
		tNG_deleteThumbnails($folder, $oldName, '');
	}
	/**
	 * the main method, execute the code of the class
	 * return mix null or error object
	 * @access public
	 */
	function Execute() {
		$ret = NULL;
		$baseFolder = KT_realpath($this->baseFolder);
		if ($this->rename == false && $this->dbFieldName != '') {
			$fileName = $this->tNG->getSavedValue($this->dbFieldName);
		} else {
			$fileName = KT_DynamicData($this->renameRule, $this->tNG, '', true);
		}
		$folder = KT_DynamicData($this->folder, $this->tNG, '', true);
		// security
		if (substr(KT_realpath($baseFolder . $folder . $fileName), 0, strlen($baseFolder)) != $baseFolder) {
			$ret = new tNG_error("FOLDER_DEL_SECURITY_ERROR", array(), array(dirname(KT_realpath($baseFolder . $folder . $fileName, false)), $baseFolder));
			return $ret;
		}
		if ($fileName != "") {
			$fullFileName = $baseFolder . $folder . $fileName;
			if (file_exists($fullFileName)) {
				$delRet = @unlink($fullFileName);
				if ($delRet !== true) {
					$ret = new tNG_error('FILE_DEL_ERROR', array(), array($fullFileName));
					$ret->setFieldError($this->fieldName, 'FILE_DEL_ERROR_D', array($fullFileName));
				} else {
					$path_info = KT_pathinfo($fullFileName);
					$this->deleteThumbnails($path_info['dirname'] . '/thumbnails/', $path_info['basename']);
				}
			}
		}
		return $ret;
	}
}
```
I think there is are an option to unlink the old file after uploading the new one.

**Comment by twistedpixel** [comment]
I’m afraid I still don’t see the problem. Once uploaded, delete the old image and move the new image to where the deleted one used to be.

This library is intended to get the image from the source computer to the server as safely as possible but it doesn’t handle replacing images on the server after that. That’s up to you and it’s really quite simple if you keep track of the image names in your database.

Sorry if I’m missing something here!

**Comment by jodyshop** [comment]
Hello,
Thank you for your responses :)

Well, I think it was a programming issue in my side, but your plugin or script only upload images or files without checking if the old files already exist.

I can explain as follow:

1- User edit profile
2- User choose a photo for the profile
3- User click save to update the profile.

Each time the user uploads a new (or even the same profile photo) it uploaded (and renamed) to be as if a new one, and leave the old (prev photo) intact.

Screenshot#1
![٢٠١٩-٠٦-١٨ at ١٨-٠٠-٣١](https://user-images.githubusercontent.com/28163331/59700245-40196f80-91f3-11e9-9823-cab84cdece2a.png)

![٢٠١٩-٠٦-١٨ at ١٨-٠١-١٥](https://user-images.githubusercontent.com/28163331/59700252-43acf680-91f3-11e9-8c42-6f5d702e7eaa.png)

![٢٠١٩-٠٦-١٨ at ١٨-٠١-٤٩](https://user-images.githubusercontent.com/28163331/59700262-460f5080-91f3-11e9-98ad-a590e7bce8e4.png)

So, a new photo uploaded without removing the old one, If I have 1 million users, and every user uploaded 10 photos (and only uses 1) then I'll get 9 million unused orphaned files.

Even if I refreshed the page, a new photo uploaded (because of browser history).
Check this#: I click refresh 4 times (before leaving the page)

![٢٠١٩-٠٦-١٨ at ١٨-٠٦-١٤](https://user-images.githubusercontent.com/28163331/59700553-d483d200-91f3-11e9-9c98-14809fcc855d.png)

And I get this:
![٢٠١٩-٠٦-١٨ at ١٨-٠٦-٣٢](https://user-images.githubusercontent.com/28163331/59700600-ecf3ec80-91f3-11e9-96b0-26df52bdf8fd.png).

Can you imagine how orphaned files are there?

**Comment by twistedpixel** [comment]
Yes but as I said before: you should be keeping track of old files and removing them yourself as you upload new ones. The library doesn’t need to handle that as it is one single use case and not something many developers would want.

It’s very simple to save the image name to a database record for the user, upload the new file, delete the old image (using the name in the DB record) and then updating the DB record with the new image name.

**Comment by jodyshop** [comment]
Yes, you're right of course, I have updated my code to enable deletion of the old file once the new one uploaded (as you recommended).

Here is the new code:

```
if($_FILES && $_FILES['avaimage']['name']){
//check current photo
$stmt = $db->prepare("SELECT avatar FROM users WHERE id=:uid LIMIT 1");
$stmt->bindValue(':uid', $uid, PDO::PARAM_INT);
$stmt->execute();
$result = $stmt->fetchAll(PDO::FETCH_ASSOC);
$icheck=$result[0];
if ($icheck['avatar']) {
@unlink("images/avatars/".$icheck['avatar']);
}else{
$error='Please check photo';
$continue=false;	
}
}
```

**Comment by twistedpixel** [comment]
Ah come on, do it properly with file_exists() instead of that lazy error suppression rubbish!

😛

**Comment by jodyshop** [comment]
Yes! I did it exactly as you told :)
Thank you for the great help and fast responses.
