### ISSUE TITLE
Packagist version outdated? Util functions not found thru namespace? And other bugs.

### ISSUE THREAD

**Issue by chris001** [samayo/bulletproof#108]
1. It looks like the version on packagist is outdated. The code installed by composer from packagist is missing a lot of parameters for the `resize` function, compared to the version of that function on github.
2. The `resize` function is not automatically found and loaded by invoking it thru the namespace `Bulletproof\Utils\resize()`, it only works when you explicitly do:
`require_once "vendor/samayo/bulletproof/src/utils/func.image-resize.php";` 
then do:
`Bulletproof\Utils\resize($image->getFullPath(), $image->getMime(), $image->getWidth(), $image->getHeight(), logoResizeWidth, logoResizeHeight, true, true);`
Autoload doesn't work, and it should work for the `Utils`, you shouldn't have to do `require_once` on anything other than `vendor\autoload.php`.
3. After you call `resize()`, the `$image->getWidth()` and `$image->getHeight()` are incorrect, it's gives the old values, where are the new values?
4. After you call `resize()`, the PNG image is fully uncompressed, 4 bytes per pixel!  For example, It takes an 11KB compressed PNG image, 800x600, resizes it down to 432x319, yet the file size has grown 50X to 511KB!

**Comment by samayo** [comment]
Not much attention is paid to the image manipulation functions, I don't know why you are getting all these issues with it, but I will check tonight. 👍

**Comment by samayo** [comment]
I have to close this. The problem here is the image utils are not part of the whole idea behind bulletproof, I might remove it in the future and redirect people to http://image.intervention.io/ but can't decide right now, it depends on the work required to maintain these classes. But I have added this to #107 if I decide to keep them, I will work on the issues you mentioned.
