### ISSUE TITLE
How do i upload multiple image, rename and create thumbnail

### ISSUE THREAD

**Issue by sanoj26692** [samayo/bulletproof#111]
I tried using your library to upload multiple images with below code 

         require_once "/src/bulletproof.php";
        $image_path = '/upload';
        $image = new Bulletproof\Image($_FILES);
        $image->setSize(200, 716800);

        if ($image["pictures"]) {
            $upload = $image->upload()
                    ->setName(uniqid())
                    ->setLocation($image_path, 0777, TRUE);

            if ($upload) {
                echo $upload->getFullPath(); // uploads/cat.gif
            } else {
                echo $image->getError();
            }
        }
        ?>
        <form method="POST" enctype="multipart/form-data">
            <input type="hidden" name="MAX_FILE_SIZE" value="1000000"/>
            <input type="file" name="pictures"/>
            <input type="submit" value="upload"/>
        </form>

i have set file upload location and rename method

`$upload->getFullPath();` echo it is been uploaded to `/upload/5de02d6bc052a.jpeg`

but when [
![Untitled](https://user-images.githubusercontent.com/7949017/69831010-7f8dc280-124d-11ea-87cf-2dbb91ff9e42.png)
](url)

the location and renaming is different.  Is there any way i can upload multiple images rename and create thumbnail and save file name to sql.

Can it be done..?

**Comment by twistedpixel** [comment]
I might be wrong but shouldn’t upload() be *after* setLocation() and setName()? I haven’t checked the source but I would imagine those need to fire first unless they are functions to move and rename the file after upload.

**Comment by sanoj26692** [comment]
Is there any way i can upload multiple images rename and create thumbnail and save file name to sql.

**Comment by twistedpixel** [comment]
Bulletproof is a library purely for uploading the files. You will need to code the functionality you mention. InterventionImage is an excellent image library, you should check it out.

**Comment by samayo** [comment]
@sanoj26692 please read the documentation, there is no reference of using upload() before setName() or setLocation() and you are doing the opposite of what is mentioned, so your first errors are from not reading the doc, which is less than 1 page tbh.

For your second question, yes all you mentioned is possible, check how multiple upload works in php, you probably need to add one line of code for that and the rest (rename, thumbnail) is in the doc and you can insert the json getJson() response in your db
