### ISSUE TITLE
File upload not working in linux server

### ISSUE THREAD

**Issue by ramenknight** [samayo/bulletproof#117]
The image upload works fine with Xampp in windows but not working when I moved it to a production linux server. It throws the following error:

"Fatal error: Uncaught Error: Call to undefined function ImageUpload\exif_imagetype()"

Any idea why this is happening and how I can fix it?

**Comment by twistedpixel** [comment]
[https://stackoverflow.com/questions/16175702/call-to-undefined-function-exif-imagetype](https://stackoverflow.com/questions/16175702/call-to-undefined-function-exif-imagetype)

Does nobody know how to Google errors anymore? 😂

**Comment by ramenknight** [comment]
Thank you for the help twistedpixel.

I'm still a beginner, I did tried to find on Google but without success. Thanks for showing me the right direction.
