### ISSUE TITLE
How to Save in JPG (instead of JPEG)?

### ISSUE THREAD

**Issue by ramenknight** [samayo/bulletproof#118]
For some reason bulletproof is saving my uploads in JPEG instead of JPG. Is there a way to change that? And how I can do it? 

Thanks for the help.

**Comment by samayo** [comment]
Thia may mean that the original image you are uploading is encoded as jpeg but the filename was jpg, so the library reads the metadata and changes the output accordingly, try it with other jpeg file and let me know

**Comment by ramenknight** [comment]
Seems that all JPG images uploaded are being saved as JPEG... :(

**Comment by samayo** [comment]
There is no part in the code that changes JPG to JPEG, moreover there is absolutely no difference between jpg/jpeg (https://www.google.com/search?q=jpg+vs+jpeg) so you can just change the extension to jpg using php's rename function https://www.php.net/manual/en/function.rename.php

**Comment by samayo** [comment]
let me know if you need more help
