### ISSUE TITLE
Svg upload ?

### ISSUE THREAD

**Issue by lukesvec** [samayo/bulletproof#119]

**Comment by samayo** [comment]
Sorry not supported right now, will try to add it in the next cycle

**Comment by samayo** [comment]
Seems like `exif_imagetype` doesn't detect SVGs as valid image types, there might be also an issue with checking the pixel size, as bulletproof does for other images types (png, jpg, jpeg...) 

So, maybe it's not better to implement this feature for now, sorry :)
