### ISSUE TITLE
Bulletproof - change image that was uploaded

### ISSUE THREAD

**Issue by sarelvdm** [samayo/bulletproof#120]
Hi, this relates to bulletproof class. How can you change an image that was previously uploaded on an website without re-uploading it.

**Comment by samayo** [comment]
If you want to re-upload, you must delete thr first image and re-upload it again, if you want to resize, crop or watermark uploaded images, you can use the functions in the folder "utils". 

There is no feature provided by the class to change uploaded images.

Just delete the old image and upload a new one with the old name, mime, location

**Comment by sarelvdm** [comment]
I have 6000+ images that relates to my products, I need to validate each images, was hoping i could do it with bulletproof, any ideas how to do it?

**Comment by samayo** [comment]
If all your images are in the same dir or you know the path for all, then you can do it without this library, just use php functions to check image mime, height, width, pixel ...

**Comment by sarelvdm** [comment]
most of them in one directory, I can search the net for sample code, you dont perhaps have a class that was written to handle images (image mime, height, width, pixel etc)

**Comment by sarelvdm** [comment]
I done a search.... https://github.com/HansF/BulletProof/blob/master/ImageUploader/BulletProof.php

**Comment by samayo** [comment]
I guess you can do that with this class, if you read the readme you will understand. But I suggest using single php functions to validate the images and create a loop to iterate through these images

**Comment by sarelvdm** [comment]
thanks...

**Comment by sarelvdm** [comment]
Hi, im n bit nervous to write my own image cleanup routine, I understand images can be used to hack sites. The images could be ok but cant proof that, I have 10 063 Images, all relates to products.
I would like to run it though Bulletproof to sanitize it. Can you please adapt Bulletproof to scan  folder images as well, please... this would help me a lot... please consider

**Comment by samayo** [comment]
Hi, I think you must this question on Stackoverflow. I made this library to be only for uploading images, and from time to time I am even optimizing the code to make simpler to read. So, I can not add an additional code to accommodate the request of one person. It just doesn't make sense and I have no time. 

Ask this on Stackoverflow, just clearly and maybe link your question here and I might provide another solution, if you explain your issue and what you have tried clearly.
