### ISSUE TITLE
Upsizing not working

### ISSUE THREAD

**Issue by sarelvdm** [samayo/bulletproof#121]
Hi,

Can you please check the resize function. think its a bug..

function resize($image, $mimeType, $imgWidth, $imgHeight, $newWidth, $newHeight, $ratio = false, $upsize = true, $cropToSize = false)

it downsize to the correct size but the upsizing dont happen. Image stays the smaller size.. $upsize is set to true...

 
                            $upload->getMime(),
                            $upload->getWidth(),
                            $upload->getHeight(),
                            1000,
                            1000,
                            true,
                            true,

**Comment by samayo** [comment]
Can you try this version? https://github.com/samayo/bulletproof/blob/v4.0.0/src/utils/func.image-resize.php 

let me know if it works

**Comment by sarelvdm** [comment]
Hi, still not working.

If I upload large image 
3385 x 2250 it creates 1000 x 664 this is correct...
if I upload small image 
197 x 255 it should enlarge to fit in 1000 x 1000 (im not cropping)
the result should be 1000 x ?. it output 197 x 255

**Comment by sarelvdm** [comment]
Hi, found the bug...
 if ($ratio == true) {
        $source_aspect_ratio = $imgWidth / $imgHeight;
        $thumbnail_aspect_ratio = $newWidth / $newHeight;
        if ($imgWidth <= $newWidth && $imgHeight <= $newHeight) {
            //$newWidth   //Use the $newwidth   -- correct
            $newHeight = $height; //use the $height --- correct
          //  $newWidth = $imgWidth; // old
          //  $newHeight = $imgHeight; // old
          
        } elseif ($thumbnail_aspect_ratio > $source_aspect_ratio) {
            $newWidth = (int) ($newHeight * $source_aspect_ratio);
            $newHeight = $newHeight;
        } else {
            $newWidth = $newWidth;
            $newHeight = (int) ($newWidth / $source_aspect_ratio);
          
        }
    }

**Comment by sarelvdm** [comment]
If you done the resizing of the image would it be possible to add an canvas or transparent background  to the image.

**Comment by samayo** [comment]
Yes, if you use the watermark function. I will try to fix this bug

**Comment by samayo** [comment]
I'm choosing to remove the utils due to time in managing the lib and to keep the library simple

**Comment by brakai295** [comment]
> Hi, found the bug... if ($ratio == true) { $source_aspect_ratio = $imgWidth / $imgHeight; $thumbnail_aspect_ratio = $newWidth / $newHeight; if ($imgWidth <= $newWidth && $imgHeight <= $newHeight) { //$newWidth //Use the $newwidth -- correct $newHeight = $height; //use the $height --- correct // $newWidth = $imgWidth; // old // $newHeight = $imgHeight; // old
> 
> ```
>     } elseif ($thumbnail_aspect_ratio > $source_aspect_ratio) {
>         $newWidth = (int) ($newHeight * $source_aspect_ratio);
>         $newHeight = $newHeight;
>     } else {
>         $newWidth = $newWidth;
>         $newHeight = (int) ($newWidth / $source_aspect_ratio);
>       
>     }
> }
> ```

This bug should be fixed. It just took me 2 days to find the problem!
