### ISSUE TITLE
Readme examples are referencing wrong methods (setLocation is now setStorage ) 

### ISSUE THREAD

**Issue by chrlilje** [samayo/bulletproof#124]
Several methods have changed names, but the Readme is not updated
setLocation() is now setStorage()
getFullPath() is now getPath()

Those are the once I have stumbled across.

**Comment by samayo** [comment]
Hi, sorry I updated the master branch but the library is still stable with the last version. I will push the changes soon. Thanks for the info.

**Comment by utan** [comment]
Well, the main doc hasn't been updated still.

**Comment by samayo** [comment]
Sorry, I will update it soon :)

**Comment by samayo** [comment]
finally ... :/
