### ISSUE TITLE
Constant 'FILTER_SANITIZE_STRING' is deprecated

### ISSUE THREAD

**Issue by DominikTV** [samayo/bulletproof#130]
The filter FILTER_SANITIZE_STRING got deprecated in PHP 8.1 and should be replaced with something more modern in the future.

https://github.com/samayo/bulletproof/blob/f7d30afa984dcf6540eee89730842c426dd13e55/src/bulletproof.php#L302

**Comment by samayo** [comment]
Thank you, the library was supposed to support PHP 5.3 and up, so I will find some alternatives

**Comment by samayo** [comment]
removed, sorry for the delay
