### ISSUE TITLE
Bulletproof and webp format.

### ISSUE THREAD

**Issue by sarelvdm** [samayo/bulletproof#146]
Hi,

Does Bulletproof support .webp format?
done a test to see if it detects the .webp format, it does, but you can't resize an Image.

Do you have a updated version.

Thanks

**Comment by samayo** [comment]
Hi sorry for the delay. When I made the library at first I wanted to support wide-variety of image types but some like .webp were never fully implemented. As of now you can only upload and manipulate the standard image types like jpeg, png, gif.

Maybe in the future I will implement more if time permits.
