### ISSUE TITLE
Can I upload multiple images?

### ISSUE THREAD

**Issue by mmx38** [samayo/bulletproof#26]
Hi,

As a really newbie, I would like to ask if there is any way to upload multiple images.. 

Is there any example ?

Thanks!

**Comment by samayo** [comment]
Yes, you can upload multiple images, but bulletproof has nothing more to provide, I suggest you check php.net for [multiple file upload](http://php.net/manual/en/features.file-upload.multiple.php) for more. On the site of bulletproof, the only thing you can do is, use a foreach() loop to the upload() method

**Comment by benjibee** [comment]
For anyone who stumbles across this later, it may save you some time to consider [this function given as a comment](http://php.net/manual/en/features.file-upload.multiple.php#53240) in the PHP manual page.

It will loop over the bizarrely structured $_FILES array and return something that can be looped easily and passed to Bulletproof.

**Comment by samayo** [comment]
I agree with benjibee.

**Comment by mushzinho** [comment]
pass $_FILES to this function ->
`	function reArray($files){

		$file_array = array();
		$file_count = count($files["image"]["name"]);
		$file_keys = array_keys($files["image"]);

		for ($i = 0 ; $i < $file_count ; $i++){
			foreach ($file_keys as $key) {
				$file_array[$i][$key] = $files["image"][$key][$i];
			}
		}
		return $file_array;
	}`
use them new array to pass each element for the class
