### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by plehnet** [samayo/bulletproof#28]
While the referencing of that specific Bible verse is actually pretty interesting in this context, it's important for both open source and commercial projects that external libraries have legally enforceable licenses.

Please consider adding an actual license to this project.  The [MIT license](http://en.wikipedia.org/wiki/MIT_License) is very short and seems to match your intent, for example.

**Comment by PeeHaa** [comment]
+1 I thought the exact same thing when reading that

**Comment by samayo** [comment]
thanks, MIT license will be used upon the release of v2.0
