### ISSUE TITLE
Resize has variable name conflict

### ISSUE THREAD

**Issue by Mknsri** [samayo/bulletproof#34]
Hi,

You use the same $image-variable for the image path parameter and for imagecreatefromstring() and this can cause the rezise to fail with a warning:

    Warning: imagejpeg(): supplied resource is not a valid stream resource in

I simply changed lines 42-55 to fix this:

    $imageFromString = imagecreatefromstring($imgString);
    $tmp = imagecreatetruecolor($newWidth, $newHeight);
    imagecopyresampled(
        $tmp,
        $imageFromString,
        0,
        0,
        0,
        0,
        $newWidth,
        $newHeight,
        $imgWidth,
        $imgHeight
    );

**Comment by samayo** [comment]
hi, thanks for poiting out this flaw, can you send a pr so I call merge it now? if not no problem.

**Comment by Mknsri** [comment]
#36 Heres the pr, I messed up the first one and canceled it
