### ISSUE TITLE
Call to a member function getLocation() on null

### ISSUE THREAD

**Issue by bartlomiejmatlega** [samayo/bulletproof#37]
Hello. I try to use this lib with example from main page. I get error: 

> Fatal error: Call to a member function getLocation() on null in /opt/lampp/htdocs/bb/vendor/samayo/bulletproof/src/bulletproof.php on line 479

And 479 line:
> $location = $this->setLocation()->getLocation();

Any one has the same problem?

**Comment by samayo** [comment]
You are using the outdated version, download it again this bulletproof file only has 432 lines

**Comment by samayo** [comment]
let me know if you get any issues

**Comment by bartlomiejmatlega** [comment]
Thanks for reply. When i use 
> php composer.phar require samayo/bulletproof:2.0.*
composer gives me version 2.0.0 which has 510 lines :( 
I'll try download it manually :)

**Comment by samayo** [comment]
Oh thanks for that, I have pushed 2.0.1 now, all should be ok.
