### ISSUE TITLE
MVC intergreation?

### ISSUE THREAD

**Issue by ArneAnka** [samayo/bulletproof#38]
is it possibel to intergreate bulletproof into a mvc app? 

Im rather unfamiliar with controllers and models.

**Comment by samayo** [comment]
Yes it is. The fact that it is a one-class library plus the namespacing makes it possible to include it in any app. 
You can just download bulletproof in your vendors dir use an autoloader to require it, 

```php 
use bulletproof\image as image; 

class HomeController extends SomeController{
  public function index(){
    $image = new Image($_FILES);
 }
}

In short, it is very simple.
