### ISSUE TITLE
setDimensionParameter minWidht, minHeight?

### ISSUE THREAD

**Issue by ThomasBevolution** [samayo/bulletproof#40]
Hi , I'm working with your class .
I just noticed , the upload method check the dimension of the image.
But the minHeight and minWidth - is checked by static value. (4)

        if($image->height < 4 || $image->width < 4){
            $image->error = "Invalid! Image height/width is too small or maybe corrupted"; 
            return ;
        }

It would be possible to extend the method setDimension?
setDimension ( $maxWidth , $maxHeight  ,  $minWidth , $minHeight ) ; 

```
if($image->height < $minHeight || $image->width < $minWidth ) {
  $image->error = "Invalid! Image height/width is too small or maybe corrupted"; 
  return ;
 }
```

This would be more flexible for daily work .

Best regards Thomas

**Comment by samayo** [comment]
It is possible to extend it as `setDimention($maxWidth, $maxHeight, $minWidth, $minHeight){}` but the point here is that, if image is less than 4px in height/width it should not be uploaded. 

You do know if you want to upload image based on dimention, you can do 

```php
if($image->getHeight() < 10){
   // image must be more than 10px in height
}
```

So, if you are trying to upload after validating image height/width there is a better way.
