### ISSUE TITLE
Unexpected '[' on line 91

### ISSUE THREAD

**Issue by suprdave23** [samayo/bulletproof#41]
Hello!

I am attempting to setup just the example you have in the readme. When viewing the page I get a PHP error, "unexpected '[' in bulletproof.php on line 91".  Looking at that line I am not seeing any syntax errors. 

I am running this with PHP 5.3. Is there any minimum system requirements for this script to work?

**Comment by suprdave23** [comment]
I am running this on a dev box that has easy access to multiple PHP versions, so I've upped the version to 5.4 and that error has gone away.

I still cannot seem to upload images though. When I select an image and click "upload" nothing happens, the page just refreshes. I placed some "crumbs" in the form of an echo inside the if statement (if $image["ikea"]) and it never seems to pass that check.

**Comment by samayo** [comment]
Yes. Minimum requirement is PHP 5.4. So you need to to change 
```php 
public function __construct(array $_files = [])
``` 
to 
```php 
public function __construct(array $_files = array())
``` 
on line 91. 

Any array declaration `$x = []`, should be `$x = array()` 

this is due to the fact that short form array syntax `[]` were only introduced in php 5.4
