### ISSUE TITLE
getMime returns nothing

### ISSUE THREAD

**Issue by pixelpaulaus** [samayo/bulletproof#46]
getMime isn't working.
always returns an error even tho it is a correct format i am uploading.

    if($image->getMime() == "jpeg" || $image->getMime() == "jpg" || $image->getMime() == "png" || $image->getMime() == "gif"){
					//all good
				}else{
				  $formerror[]='Invalid file format for logo';
			    }

**Comment by pixelpaulaus** [comment]
if i echo the getMime, it is always blank.
useless.

**Comment by samayo** [comment]
just a tip, you can use `in_array` function next time, like this:

```php
if(in_array($image->getMime(), ['gif', 'png', 'jpeg', 'jpg'])) {
   // ...
}
```
