### ISSUE TITLE
keep transparency on resize?

### ISSUE THREAD

**Issue by pixelpaulaus** [samayo/bulletproof#47]
is it possible to keep the transparency on a gif or png on a resize? as it seems to get filled with black when i do it.

**Comment by samayo** [comment]
Currently no, but I will add that in the future, not just sure when.

**Comment by ncou** [comment]
Hi,

You need to add the following code : 

    imagealphablending($tmp, false);
    imagesavealpha($tmp, true);

In the resize plugin, after the instruction : "$tmp = imagecreatetruecolor($newWidth, $newHeight);"

**Comment by samayo** [comment]
done! Not sure why it took me this long, your help was awesome :+1:
