### ISSUE TITLE
IMG Crop 

### ISSUE THREAD

**Issue by wycior** [samayo/bulletproof#50]
I think Crop need small improvement - cause now its only croping and mostly missing the needed content - here what i did -  1st thing is to resize as close to the needed size - most important  we have to check out which value is bigger width or height, then we may crop - so most of the content remains

Check it out - small change but i think good one.

Here is the code 

 function crop($image, $mimeType, $imgWidth, $imgHeight, $newWidth, $newHeight){

    switch ($mimeType) {
        case "jpg":
        case "jpeg":
            $imageCreate = imagecreatefromjpeg($image);
            break;

        case "png":
            $imageCreate = imagecreatefrompng($image);
            break;

        case "gif":
            $imageCreate = imagecreatefromgif($image);
            break;

        default:
            throw new \Exception(" Only gif, jpg, jpeg and png files can be cropped ");
            break;
    }
		
	
	$thumb_width = $newWidth;
	$thumb_height = $newHeight;

	$width = $imgWidth;
	$height = $imgHeight;

	$original_aspect = $width / $height;
	$thumb_aspect = $thumb_width / $thumb_height;

	if ( $original_aspect >= $thumb_aspect )
	{
		// If image is wider than thumbnail (in aspect ratio sense)
		$new_height = $thumb_height;
		$new_width = $width / ($height / $thumb_height);
	}
	else
	{
		// If the thumbnail is wider than the image
		$new_width = $thumb_width;
		$new_height = $height / ($width / $thumb_width);
	}

	$thumb = imagecreatetruecolor( $thumb_width, $thumb_height );

// Resize and crop
	imagecopyresampled($thumb,
                   $imageCreate,
                   0 - ($new_width - $thumb_width) / 2, // Center the image horizontally
                   0 - ($new_height - $thumb_height) / 2, // Center the image vertically
                   0, 0,
                   $new_width, $new_height,
                   $width, $height);

    if (!$thumb) {
        throw new \Exception("Failed to crop image. Please pass the right parameters");
    } else {
        imagejpeg($thumb, $image);
    }

}

Br

**Comment by samayo** [comment]
Hi, thanks. I'm not sure I get what you are saying with this: 
> ..cause now its only croping and mostly missing the needed content..
The crop function, only does what it's told, i.e. to crop the image from the center. If you have a passport picture, you need to crop only 10x10 pixels, it will start from the middle and crop 5pixels sideways, top/bottom. There is no way to add any improvement to this func imho, but you can send a PR with your improvement and I'll try it for more insight. 

thanks :+1:

**Comment by wycior** [comment]
Ahh i was looking for function which adjust photo to some specyfic size  - if its to wide then it have to be cutted a bit  etc- so i think i made a small mistake in last post... didnt saw how you build resize function (which is what i was looking for - but alredy adust crop function to my needs:>) - sorry for messing. Please delete subject.
