### ISSUE TITLE
Exif module not actif

### ISSUE THREAD

**Issue by ncou** [samayo/bulletproof#52]
Hi,

Very nice plugin. There is an error on the "exif_imagetype" function not found, if the module is not actif in your php.ini file.

I thin you shoud made a check on "var_export(extension_loaded('exif'));" if it's "false", then show a more prettier error message.

Don't you think ?

Keep up the good work.

**Comment by samayo** [comment]
Yeah, this is a good catch. I had actually made note of the exit plugin as a requirement in the readme, but somehow it is no longer there. I think It should check for that plugin and throw an error, thanks. :+1:

**Comment by ncou** [comment]
Thank you for your quick answer :) good news.
I think i have spot 2 small mistakes ;

- In the bullet.php file the picture heightxwidth are 500x500**0** i think is 500x500.
- in the util readme.md file, there is the sentence : "The crop() method supports resizing by ratio, checkout the file for more." in fact it's the resize and not the crop methode who support ratio.

By the way i think the ratio and upscale param should be added in the documentation.

anyway, great plugin.
Keep up the good work.

**Comment by samayo** [comment]
done! #57 thanks :+1:
