### ISSUE TITLE
Resize plugin - Upsize not working ?

### ISSUE THREAD

**Issue by ncou** [samayo/bulletproof#53]
Hi,

I try to resize my picture with the new size = 200x200px
If i got a bigger picture, all work fine, but on a small picture 186x102, with the upsize param = true, i don't get a picture at the expected 200x109 mimension, but the same image at 186x102, the dimension is inchanged.

What am i missing ? for me the upscale parameter should strech my picture on width axis or height axis.

Thank you for your help

**Comment by samayo** [comment]
I'll check, but I never liked the idea to stretch images beyond their original size. There are other libraries for that that will not degrade the quality. So, I only made it to resize to smaller figure, but someone added the upsize param, which I have not really tested. I'll check.

**Comment by ncou** [comment]
Thank you.

**Comment by samayo** [comment]
No problem. I don't have much time right now to fix this issue, but I will in the coming weeks. I will also enable errors catchable with exception in the next release (v3.0.0)

**Comment by ncou** [comment]
Great news.

For the upscaling, i don't have made some tests but i think with an interpolation to "hermite or mitchell" +  the "imagescale()" function the resize could be loosless

http://php.net/manual/en/function.imagesetinterpolation.php
http://php.net/manual/en/function.imagescale.php

Have a good day.

**Comment by samayo** [comment]
Note sure about this anymore, if you are trying to reference #56 it's aleady done :) 

thanks and sorry for the delay, been super bussy
