### ISSUE TITLE
$image->setDimension, the other way around?

### ISSUE THREAD

**Issue by ArneAnka** [samayo/bulletproof#54]
Hi!

Just notice that:

```php
// set max width/height limits (in pixels)
$image->setDimension($width, $height); 
```

Seems to be

```php
// set max width/height limits (in pixels)
$image->setDimension($height, $width); 
```

I have a image with the following settings
<img width="350" alt="skarmavbild 2016-06-27 kl 11 46 23" src="https://cloud.githubusercontent.com/assets/5988810/16375687/e0e7278a-3c5c-11e6-857a-f5299274304e.png">

And i had to change the order to

```php
// set max width/height limits (in pixels)
$image->setDimension('960', '1080'); 
```

Thanks!

Or should i make a pull request?

**Comment by samayo** [comment]
Haven't checked this yet (i'm on mobile). If you are certain, send a pr if you can, and thanks :)
