### ISSUE TITLE
Bad String in JSON 

### ISSUE THREAD

**Issue by pararang** [samayo/bulletproof#60]
Hi,
Nice project. FYI, Just try it on my API project and use the original error message when parsing it to JSON. Got "Bad String" on invalid image dimension error message.

Will be a bad string in JSON because of backslash:
`"message":"Image height/width should be less than ' 1000 \ 1000 ' pixels"` 

Just change it to forwardslash to be acceptable in JSON format:
`"message":"Image height/width should be less than ' 1000 / 1000 ' pixels"`

is there any reason why you use the backslash?

Thanks.

**Comment by samayo** [comment]
@pararang Thanks. It was a PR I didn't inspect enough, can you check and let me know if it's working :)

**Comment by pararang** [comment]
@samayo u r welcome, now it working. Thanks
