### ISSUE TITLE
Blank Screen When uploading more than max size

### ISSUE THREAD

**Issue by remedcu** [samayo/bulletproof#70]
Hello, I am uploading an image more than the max size, and it shows a blank page instead of an error.

Below is my code in the form:
 
    <form enctype="multipart/form-data" method="post" action="imageupload.php">
        <input type="hidden" class="form-control" name="MAX_FILE_SIZE" value="5000000"/> //For 5MB
        <input type="file" name="pictures" id="fileToUpload" />
        <button type="submit" class="btn btn-info btn-fill pull-right">Update</button>
        <div class="clearfix"></div>                                    
    </form>

And imageupload.php is as below:

    <?php
    require_once  "bulletproof/src/bulletproof.php";
    try{
        $image = new Bulletproof\Image($_FILES);
        $image->setName(time());
        $image->setLocation('images/');
        if($image["pictures"]){
            $upload = $image->upload(); 
            if($upload){
                header("Location:form.php?success=Image uploaded successfully");
            }
            else
            {
                $errormsg=$image['error'];
                header("Location:form.php?failure=$errormsg");
            }
        }
    }
    catch(\Exception $e)
    {
    echo $e->getMessage(); 
    }
    ?>

As you can see, here I have used a limit of 5MB for the images, but when I try to upload an image more than 5MB, it shows no error, just blank page.

Then I kind of played with the code, and found out that, whenever we upload images more than the limit, it goes to the else of `if($image["pictures"])` which is not written in the readme. I can simply make the else with a message that "Error: The file size is more than 5MB".

But I want to know, if there is any other way we can detect if the image is more than 5MB and give a message according to that which is already included in the bulletproof features.

**Comment by samayo** [comment]
You are trying to catch an exception which isn't thrown inside your code, or inside the bulletproof class. If you have seen the inside of bulletproof.php there are no exceptions being thrown so this won't show anything. 
```php
echo $e->getMessage(); // won't work
```
If you want to show exceptions instead of errors, then your exception block should look something like this: 

```php
try {

   if($image['foo'] && $image->upload()){
      //...
   }else{
      throw new \Exception($image['error']);
   }

} catch (Exception $e) {
    echo $e->getMessage();    
}
```
Also, if you are seeing a blank page, make sure you have set errors to be displayed, or put this in your script. 
```php
error_reporting(E_ALL);
ini_set('display_errors', 1);
```
check these and let me know.

**Comment by remedcu** [comment]
Can you please tell me a way to show error related to the size like "File uploaded is more than 5MB" when the uploaded file is more than 5 MB? As I have already set the hidden field "MAX_FILE_SIZE" value as 5000000

**Comment by samayo** [comment]
Okay, after some time I found the issue, this is most likely a bug with the newer version of bulletproof, as the previous version shows this error well. I have created a dev branch and added this code 

https://github.com/samayo/bulletproof/blob/dev/src/bulletproof.php#L127-L129 

Your code should look like this to show the error:
```php 
$image = new \Bulletproof\Image($_FILES);

if($image['pictures']){
 // upload
}else{
  var_dump($image['error']); // error will be shown here
}
```

make sure to download the [dev](https://github.com/samayo/bulletproof/tree/dev) branch or add those [lines](https://github.com/samayo/bulletproof/blob/dev/src/bulletproof.php#L127-L129) to your bulletproof class. 

I will try to find a better way to handle this, and will leave this open until I fix the issue

**Comment by remedcu** [comment]
It's working fine now. Thank you for the patch.
