### ISSUE TITLE
$image->getMime() giving blank in this release

### ISSUE THREAD

**Issue by remedcu** [samayo/bulletproof#71]
Well, I am back with another error.

I was trying to get the type of the file using `$image->getMime();`

And I get blank all the time instead of jpeg or gif or any other image format.

Can you check what is the problem with this version?

**Comment by samayo** [comment]
Can you paste the code you are using?

**Comment by remedcu** [comment]
I just wanted to get the extension, the code is below:

```
require_once  "../../bulletproof/src/bulletproof.php";
$image = new Bulletproof\Image($_FILES);
$imagestype = $image->getMime();
echo $imagetype;

```
The above one echoed blank.

**Comment by samayo** [comment]
If the image is not uploaded, you can't get the mime type. Make sure `if($image['pictures']){}` yields true first. then check it inside the block

**Comment by remedcu** [comment]
Ok, I editted the code:

```
$image = new Bulletproof\Image($_FILES);
$imagestype = $image->getMime();
$image->setLocation('images/');
if($image["pictures"]){
    $imagename=time().'.'.$imagestype;
    $image->setName($imagename);
    $upload = $image->upload();
```

The image get's uploaded but the name is always UNIX timestamp with a dot (.) but no extension.

**Comment by remedcu** [comment]
What I want is the name of the file with the extension so that I can store than in database as well. The image gets saved correctly with the correct extension, but I also want the complete name.

Like if I am uploading a image called abc.png

After uploading the file gets saved as 12345678.png
Also I need the name "12345678.png" stored in a variable. Right now I only get the name as "12345678"

**Comment by samayo** [comment]
You can't use `getMime()` before the image is uploaded. PHP wouldn't know about it. Also, why are you trying hard to give it a name when you can just leave it for the library to generate a name for it? 

I just tried this and it works. 
```php
$image = new Bulletproof\Image($_FILES);
$image->setLocation('images');
if($image['pictures']){
   // $image->setName(time());
    $upload = $image->upload();
    echo $image->getFullPath(); //  images/159a025c774ab8_pigmfqnolhkje.gif
}
```

There you have it, use `getFullPath()` to get the fill path, and `getMime()` for the ext, and `getLocation()` for the folder. If you want to assign time by UNIX then comment the code ` $image->setName(time());`

read the docs

**Comment by remedcu** [comment]
Thank You, I tried the getFullPath and it worked.

Though the getMime still didn't worked for me (when I am uploading an image only)

**Comment by samayo** [comment]
Your welcome :) 

And yes, PHP can only get the mimetype once the image is uploaded to a temporary file.
