### ISSUE TITLE
Wrong default permission

### ISSUE THREAD

**Issue by DmitryMyadzelets** [samayo/bulletproof#73]
The default permission for `mkdir` is `0666` ([see the code](https://github.com/samayo/bulletproof/blob/master/src/bulletproof.php#L229)), i.e. `rw-` for the owner. It doesn't allow neither create files nor move them there from a temporary directory. The correct permission seems should be `0766`.

**How to reproduce the bug**

In the example code insert the line which changes the location, as shown:
```php
$image = new Bulletproof\Image($_FILES);
$image->setLocation('/var/tmp/bulletproof'); // or /tmp/bulletproof
```
Then try to upload a file. You'll get the error `Upload failed, Unknown error occured` (btw, `occured` should be changed to `occurred`). Check the directory permission:
```bash
ls -l /var/tmp
> drw-r--r-- 2 www-data www-data   4096 Sep  4 18:10 bulletproof
```

**Comment by samayo** [comment]
I don't think this is a bug. I can create a recursive dir with: 
```php
$image->setLocation(__DIR__ . '/foo/bar/bulletproof');
```
without applying a custom permission argument, but not when trying to upload to my `/var/tmp` .. I tried to even upload with `0777` but I get permission denied. I think this is beyond my understanding of access management for now, but I don't think it's a bug.  I will investigate later

**Comment by DmitryMyadzelets** [comment]
The example you provided fails on`mkdir` command given the **directory tree** with `-p` option. It has nothing to do with permissions (assuming you have them for `__DIR__`).

The `06??` permission allows the owner to read and write to *exiting* files. The uploader *creates* files. For that you have to have `x` on the directory.

The uploader creates a directory it can't write to, and then tries to write. Isn't it a nonsense?

But you are right, pointing to another problem. The user can set any (wrong) permission for a directory, and struggling on `undefined error`. I'd verify if the uploader has the right to create a file. Say, just [before doing it](https://github.com/samayo/bulletproof/blob/master/src/bulletproof.php#L450) we can check:

```php
        /* check if we can create a file in the directory */
        if (!is_writable($image->location)) {
            echo "The images directory \"" . $image->location . "\" is not writable!";
            return null;
        }

```

**Comment by DmitryMyadzelets** [comment]
The example you provided fails on`mkdir` command given the **directory tree** with `-p` option. It has nothing to do with permissions (assuming you have them for `__DIR__`).

The `06??` permission allows the owner to read and write to *exiting* files. The uploader *creates* files. For that you have to have `x` on the directory.

The uploader creates a directory it can't write to, and then tries to write. Isn't it a nonsense?

But you are right, pointing to another problem. The user can set any (wrong) permission for a directory, and struggling on `undefined error`. I'd verify if the uploader has the right to create a file. Say, just [before doing it](https://github.com/samayo/bulletproof/blob/master/src/bulletproof.php#L450) we can check:

```php
        /* check if we can create a file in the directory */
        if (!is_writable($image->location)) {
            echo "The images directory \"" . $image->location . "\" is not writable!";
            return null;
        }

```

**Comment by DmitryMyadzelets** [comment]
Btw, saying *writing* to directory I implied *creating* a file in it. I've struggled on this topic myself yesterday, thanks to this module, and found a good reading: https://www.hackinglinuxexposed.com/articles/20030424.html

**Comment by samayo** [comment]
👍 Will add the code, thanks for the help

**Comment by samayo** [comment]
fixed
