### ISSUE TITLE
Wrong usage of uniqid function

### ISSUE THREAD

**Issue by DmitryMyadzelets** [samayo/bulletproof#76]
I guess you wanted to add more entropy for [id generator there](https://github.com/samayo/bulletproof/blob/master/src/bulletproof.php#L265), but ended up adding `1`'s in the beginning of file names. If so, should be `uniqid('', true)` instead.

See [the manual](http://php.net/manual/it/function.uniqid.php) for details.

**Comment by samayo** [comment]
fixed
