### ISSUE TITLE
Wrong code in the example

### ISSUE THREAD

**Issue by DmitryMyadzelets** [samayo/bulletproof#77]
Seems the `$image["pictures"]` doesn't exist.

**Comment by samayo** [comment]
It does, this is a small bug related to this issue. https://github.com/samayo/bulletproof/issues/70#issuecomment-324625382 make sure to have an else statement to see browser max upload size error

**Comment by samayo** [comment]
will find a fix for this soon

**Comment by DmitryMyadzelets** [comment]
Well, I'm not sure how to measure size of a bug, but the impact of *this* bug is huge. Any server has the `MAX_FILE_SIZE` limit.

**Comment by samayo** [comment]
this is not a bug really, just something that needs a fix. this is 0 vulnerability if that is what you are thinking
