### ISSUE TITLE
Notice: Undefined index: tmp_name

### ISSUE THREAD

**Issue by elieobeid7** [samayo/bulletproof#78]
I keep getting

`Notice: Undefined index: tmp_name in /opt/lampp/htdocs/web/emall/production/app/vendor/samayo/bulletproof/src/bulletproof.php on line 413
`

**Comment by samayo** [comment]
This is strange ... let me check. Also can I see your code?

**Comment by samayo** [comment]
I'm not getting this error.

**Comment by elieobeid7** [comment]
This is my code running on Xampp 7.x on Fedora

```
<?php
require 'database_connect.php';
$image = new Bulletproof\Image($_FILES);
$imageName= base64_encode($_SESSION['admin_email']);         


$image->setName($imageName)
->setMime(array('jpeg', 'gif', 'png', 'jpg'))
->setLocation(__DIR__ . "/avatars"); 

if (isset($_POST['submit'])){

    $image->setDimension(128,128); 
    
    
    if($image["pictures"]){
  
        
        // set the max width/height limit of images to upload (limit in pixels)
        
        
        // pass name (and optional chmod) to create folder for storage
        $upload = $image->upload(); 
        
        if($upload){
            $photo = $upload->getFullPath(); // uploads/cat.gif
        }else{
            $photo = NULL;
        }
    }



        $fname = $_POST['fname'];
        $lname = $_POST['lname'];
        $email = $_POST['email'];

        $db->user[$_SESSION['admin_id']] = [
            'firstName' => $fname,
            'lastName' => $lname,
            'email' => $email,
            'photo' => $photo
        ];

} 



/* header("Location:profile.php");
exit; */
?>

```

I tried to remove setName altogether, didn't work

Please forgive my mess, I'm trying to upload a photo, then I'll clean it. getFullPath returns empty, upon checking why I receive this error. I'm using version 3.0.2.

also another error with setDimentions, I cannot do


```
$image->setName($imageName)
->setMime(array('jpeg', 'gif', 'png', 'jpg'))
->setLocation(__DIR__ . "/avatars")
->setDimension(128,28); 
```

it gives something like error boolean function, something like that forgot the error

**Comment by samayo** [comment]
Okay, at first glance this I was able to spot the issue. `$_POST` and `$_FILES` are two different arrays. One checked for posts made via your form (ex, text inputs) and the other `$_FILES` checks for file uploads. So, it is correct to see "undefined index tmp_name`... error, because you are not checking if form is submitted.


Anyway, I can't be sure right now because I am trying to find a fix to resolve the error that appears when the browser blocks the image upload due to max file constraint. If you leave that from your HTML it might work nicely, until I find a solution. For now, I was able to try this script, which is slightly modified version of your and it works as intended: 

```php
require __DIR__ . '/src/bulletproof.php'; 


$image = new Bulletproof\Image($_FILES);

$imageName = rand(1, 100) . '-foo';

$image->setName($imageName)
      ->setMime(array('jpeg', 'gif', 'png', 'jpg'))
      ->setLocation(__DIR__ . "/avatars")
      ->setDimension(128,128); 
    
    
    if($image["pictures"]){
        $upload = $image->upload(); 
        
        if($upload){
            $photo = $upload->getFullPath(); // uploads/cat.gif
            // store in db
        }else{
          echo "error while uploading " . $image['error'];
            $photo = NULL;
        }



}else{
  if($image['error']){
    var_dump($image['error']);
  }
}
```

Let me know if you have any more questions

**Comment by samayo** [comment]
Also make sure your HTML form element has the multiplart/form-data attribute eg: `<form method="POST" enctype="multipart/form-data">`

**Comment by elieobeid7** [comment]
I just tried your code as is


```
$image->setName($imageName)
      ->setMime(array('jpeg', 'gif', 'png', 'jpg'))
      ->setLocation(__DIR__ . "/avatars")
      ->setDimension(128,128); 
    
```

And the dimension error i was talking about showed up

`Fatal error: Uncaught Error: Call to a member function setDimension() on boolean in /opt/lampp/htdocs/web/emall/production/app/profile_ctrl.php:11 Stack trace: #0 {main} thrown in /opt/lampp/htdocs/web/emall/production/app/profile_ctrl.php on line 11`

**Comment by samayo** [comment]
Well, maybe that is the issue. `setLocation` method can only return `false` (boolean) only if it failed to create a dir so, maybe you have no permission. In which case, you'll be able to capture the esing your `$image['error']` method

**Comment by elieobeid7** [comment]
now it works, is it possible to resize the image?

**Comment by samayo** [comment]
Yes, just include one of the functions in the folder /utils which is for resizing images. They should work better than the actual bulletproof library

**Comment by elieobeid7** [comment]
perfect thank you, since setDimensions is annoying, better to resize it if it doesn't fit. That's why setdimensions was giving me errors, I thought it automatically resize. My bad :)

**Comment by elieobeid7** [comment]
One last question, if I let it do the naming automatically, can it guarantee unique names?

**Comment by samayo** [comment]
Yes, it will generate unique name always. Also setDimention method is for setting a limit of image width/height not resizing

**Comment by elieobeid7** [comment]
I'm uploading like this

` $photo = $upload->getName() . '.' . $upload->getMime();`

and displaying like this, once they get to the db, since I cannot store `getFullpath()`

```
$path = 'avatars/';
$avatar =$path . $user->photo;
```

Is there a way to get the relative path? I mean is there a method I didn't use in your library that makes me write less code? it's nothing I know but when I saw getFullPath I started wondering about getRelativePath or similar

**Comment by samayo** [comment]
`getFullPath()` will return the path starting from where the image is stored in ex: if you upload in images: 

`$image->setLocation(__DIR__ . '/images')` you will get the current path plus the full path before. If you want want to get only the relative path I think you should set the location as `$image->setLocation('images')`

**Comment by elieobeid7** [comment]
I can't get the image from

`  <input type="file" name="data[photo]" id="photo" class="custom-file-input"> `

it always gives an undefined variable, I tried the script above and  some other variations nothing worked

**Comment by samayo** [comment]
I think that may be because you are trying to upload multiple files. I haven't implemented that yet. You can just do a php foreach() and use the upload method to upload the images for now. Let me know if you are facing some issues to upload a single file

**Comment by elieobeid7** [comment]
I'm just uploading one file, here's the latest variation I tried

```
<? require('common/session.php');
require "common/vendor/samayo/bulletproof/src/utils/func.image-resize.php";
$image = new Bulletproof\Image($_FILES);
if (isset($_POST['submit'])){


$image->setMime(array('jpeg', 'gif', 'png', 'jpg'))
      ->setLocation(__DIR__ . "/avatars");
    
    
    if($image[$data["photo"]]){
    
        
        $upload = $image->upload(); 
        
        if($upload){
            $resize = Bulletproof\resize(
                $image->getFullPath(), 
                $image->getMime(),
                $image->getWidth(),
                $image->getHeight(),
                120,
                120
         );
            $data['photo'] = $upload->getName() . '.' . $upload->getMime();    

        }else{
          echo "error while uploading " . $image['error'];
            $data['photo'] = NULL;
        }



} else{
  if($image['error']){
    var_dump($image['error']);
  }

  
} 



/* $data = array($_POST['data']);
    $db->user->insert()
    ->data($data)
    ->run(); */

    echo $data['photo'];
}



```

I tried many other things, this is my second project using your library, the first one worked, but now I had to use array since I have a billion input fields. faster to insert them like that

**Comment by elieobeid7** [comment]
problem fixed

**Comment by samayo** [comment]
How did you fix it? I was just about to try it after work .. sorry

**Comment by elieobeid7** [comment]
not really fixed, i thought it was but not really

https://stackoverflow.com/questions/46851647/cannot-insert-input-type-file-to-array-of-html-names

I don't know why SO votes down a question if it's hard to answer, anyhow I just discovered that you cannot add file input to html name array. unless you have a solution, I'd just add it to the array using php
