### ISSUE TITLE
Upload .jpg file

### ISSUE THREAD

**Issue by ibnoe** [samayo/bulletproof#79]
When i upload .jpg file then i save 
$upload->getFilename()

i got this record 159ca9696c8d3a_mgjlfhekiqnop.jpeg

but on filesystem, 159ca9696c8d3a_mgjlfhekiqnop.jpg

**Comment by samayo** [comment]
Yes, this can happen. This is not an issue with bulletproof though. Sometimes the encoding of the image maybe incorrect (this happens with jpg/jpeg files) so, the best thing to do in this scenario is call file name and mime separately. as: 
```php
$correct_image_name = $image->getName() . '.' . $image->getMime(); 
```
Or use the `toJson()` message, that returns the true mime type. Also, can you share the image so I can debug the class better?

**Comment by ibnoe** [comment]
i think its better to check the file extension too. its same with the mime or not
![ac619469c5a66d1b1065a8d4a045a61d_t](https://user-images.githubusercontent.com/455793/30899096-b63dd742-a388-11e7-92eb-1c86e5d8f230.jpg)

**Comment by samayo** [comment]
But file extension is unreliable, it's better to read the file headers exif info. This image is simply coded incorrectly. However, i think I can fix this

**Comment by samayo** [comment]
sorry for the delay, couldn't implement a fix for this, as it's not a break from bf side but the image format is invalid. I'll add this to feature improvement, feel free to send a PR until then if you can
