### ISSUE TITLE
Check File Type

### ISSUE THREAD

**Issue by alivelimeli** [samayo/bulletproof#80]
Hello,

I've come across an article on internet: https://imperavi.com/redactor/docs/security/

There is a section about image file type detection.

What do you think about this function?

```
function is_image($image_path)
{
    if (!$f = fopen($image_path, 'rb'))
    {
        return false;
    }

    $data = fread($f, 8);
    fclose($f);

    // signature checking
    $unpacked = unpack("H12", $data);
    if (array_pop($unpacked) == '474946383961' 
    || array_pop($unpacked) == '474946383761') return "gif";

    $unpacked = unpack("H4", $data);
    if (array_pop($unpacked) == 'ffd8') return "jpg";
    $unpacked = unpack("H16", $data);
    if (array_pop($unpacked) == '89504e470d0a1a0a') return "png";

    return false;
}
```
Maybe you can add into your library?

**Comment by krahamath** [comment]
This is good but is paid library.

**Comment by samayo** [comment]
Sorry for thw delay in response OP. I'm not sure this is going to make bulletproof safer but i'll check it out

**Comment by samayo** [comment]
Sorry for the dealy

So, I see what his function does, it reads the exif info of the image header, if I am not mistaken. Which is basically what exif_imagetype() function does and I am using this for bulletproof already, so it would be redundant to add it. Let me know if you have anymore tips 
👍
