### ISSUE TITLE
Image compress

### ISSUE THREAD

**Issue by krahamath** [samayo/bulletproof#81]
Hi

It will do compress images by given value?

**Comment by samayo** [comment]
Hi, there are no compressions done bulletproof, so you need to create a custom feature for that.

**Comment by krahamath** [comment]
it will be good if this plugin has feature like tinyjpg.com (not like exactly but something like)

**Comment by samayo** [comment]
Nice idea. I will add that to the list of utils/

**Comment by krahamath** [comment]
Great! Thanks and waiting..

**Comment by aliihaidar** [comment]
Hello, I used the resize option to decrease the width and height of the image, but the size went up from 1.2MB to 10MB, anyone encountered this?

**Comment by samayo** [comment]
There has to be some error, I will check it out later today.

**Comment by krahamath** [comment]
I found this: https://github.com/colepanike/BulletProof and hope if helps you.

**Comment by krahamath** [comment]
Any update ?

**Comment by samayo** [comment]
Sorry, still didn't test it, been busy with work. will check tonight

**Comment by samayo** [comment]
@krahamath  closing this for now. I don't have any immediate plans to add image compression. Can you please check this? https://stackoverflow.com/questions/11418594/which-is-the-best-php-method-to-reduce-the-image-size-without-losing-quality if you create your own function, you can include it in bulletproof and I will add it to the main repo

cheers
