### ISSUE TITLE
getName()

### ISSUE THREAD

**Issue by playinteractive** [samayo/bulletproof#82]
Why $image->getName() doesn't get the file extension?!

Maybe you can create getNameWithExtension() or similar.

**Comment by samayo** [comment]
You can use $image->getMime() to get the extention and combine the two to get the name and extension and even getLocation() to get the directory.  Or simply use getFullPath() to get all the above three.

Check the readme for more :)

**Comment by playinteractive** [comment]
Sure, or even basename($news_file_image->getFullPath()). But it's about elegance.

Anyways great class.

Best,
