### ISSUE TITLE
string(45) "Image is larger than specified by the browser" 

### ISSUE THREAD

**Issue by elieobeid7** [samayo/bulletproof#83]
I keep getting this error

`string(45) "Image is larger than specified by the browser" `

What should that mean? By the way, not sure if correct but I noticed that I have to chmod image folder 777, don't know why 755 doesn't work.

Also my site is protected all of it by lets encrypt ssl, don't know if that has a role to play as well in any possible errors 

my code

```
<? require('common/session.php');
 require "common/vendor/samayo/bulletproof/src/utils/func.image-resize.php";
$image = new Bulletproof\Image($_FILES);
$image->setMime(array('jpeg', 'gif', 'png', 'jpg'))
    ->setLocation(__DIR__ . "/avatars");


if (isset($_POST['submit'])){
filter_var_array($_POST, FILTER_SANITIZE_STRING);
    $data = $_POST['data'];
    $cdata = $_POST['cdata'];
    $data['email'] = strtolower(preg_replace('/\s+/', '', $data['email']));
    $cdata['email'] = strtolower(preg_replace('/\s+/', '', $cdata['email']));
    $data['phone'] = preg_replace('/\s+/', '', $data['phone']);
    $cdata['phone'] = preg_replace('/\s+/', '', $cdata['phone']);
    $data['deleted']  = 0;
    $cdata['deleted'] = 0;



$image->setMime(array('jpeg', 'gif', 'png', 'jpg'))
      ->setLocation(__DIR__ . "/avatars");
    
    
    if($image["photo"]){
    
        
        $upload = $image->upload(); 
        
        if($upload){
            $resize = Bulletproof\resize(
                $image->getFullPath(), 
                $image->getMime(),
                $image->getWidth(),
                $image->getHeight(),
                120,
                120
         );
            $data['photo'] = $upload->getName() . '.' . $upload->getMime();    

        }else{
          echo "error while uploading " . $image['error'];
            $data['photo'] = '';
        }



} else{
  if($image['error']){
    $data['photo'] = '';
    var_dump($image['error']);
  }

  
} 





  
  $company = $db->company->create($cdata);
       $company->save();               
     $user = $db->user->create($data);
     $user->relate($company);
     $user->save();
}
//header("Location:index.php");
//exit;
```

**Comment by samayo** [comment]
Check the value you gave your input in:

   <input type="hidden" name="MAX_FILE_SIZE" value="1000000"/>

That value should be larger than your image size

**Comment by elieobeid7** [comment]
<input type="hidden" name="MAX_FILE_SIZE" value="1000000"/>

**Comment by elieobeid7** [comment]
ok now i increased it so much and now i get

error while uploading Image size should be at least 1 KB, and no more than 500 KB

**Comment by samayo** [comment]
Then that means check your $image->setSize ()  it means you have set your image size too low. Pass two values to that function also check the readme

**Comment by samayo** [comment]
Remember to pass the values in bytes.   So, 1000 is 1000 in kb which means 1 mb

**Comment by elieobeid7** [comment]
same error; php:

```
$min = 200;
    $max = 10000000; 
$image->setMime(array('jpeg', 'gif', 'png', 'jpg'))
      ->setLocation(__DIR__ . "/avatars");
    
    
    if($image["photo"]){
    
        
        $upload = $image->upload(); 
        
        if($upload){
            $resize = Bulletproof\resize(
                $image->getFullPath(), 
                $image->getMime(),
                $image->setSize($min, $max), 
                $image->getWidth(),
                $image->getHeight(),
                120,
                120
         );
            $data['photo'] = $upload->getName() . '.' . $upload->getMime();    
...


html

```
  <label class="custom-file">
  <input type="file" name="photo" id="photo" class="custom-file-input"  accept="image/*" onchange="readURL(this);" />
    <input type="hidden" name="MAX_FILE_SIZE" value="10000000"/>
  <span class="custom-file-control profile_pic_span">Select Picture</span> 
</label>
```

**Comment by samayo** [comment]
Can you use the same html and php code from the read me? And let me know if you get the same error

**Comment by elieobeid7** [comment]
Just did, same error, I have two possible reasons in mind, either ssl, or the fact that siteground, my hosting (shared hosting) provider doesn't specify an upload tmp_dir in php.ini so the library searches for another folder to place the uploads?

It was working great on fedora, my old laptop, now I'm deploying on server and it's not. Same code



> file_uploads On
> max_file_uploads 20
> upload_max_filesize 120 mb
> upload_tmp_dir no value
> user_dir no value
> post_max_size 128 mb
> upload_max_filesize 128 mb
> memory_limit 768 mb
> max_execution_time 120
> chmod 777 -R avatars

**Comment by elieobeid7** [comment]
tomorrow i'll try to write my own upload script to see if it's the hosting or this library, btw does this library support uploading excel files and csv?

**Comment by samayo** [comment]
The error you are getting is very specific to be tmp_dir related. And no, this library is only for images.

**Comment by elieobeid7** [comment]
If all else fails I'll create an ftp account with a demo project so you can test it

**Comment by elieobeid7** [comment]
Ok so, first of all, 755 permissions work perfectly, placing the uploads folder outside public_html doesn't work

 in bulletproof file I commented out line 433 to line 438

```
    /*    if ($files['size'] < $minSize || $files['size'] > $maxSize) {
            $min = intval($minSize / 1000) ?: 1;
            $max = intval($maxSize / 1000) ?: 1;
            $image->error = "Image size should be at least " . $min . " KB, and no more than " . $max . " KB";
            return null;
        }*/
```


Even if I hardcoded `maxSize` and `minSize`, it doesn't work, I had to comment out the code above.

Then I started getting this error


```
Notice: Object of class BulletProof\Image could not be converted to int in /home/user/public_html/common/vendor/samayo/bulletproof/src/utils/func.image-resize.php on line 16

Warning: imagecreatetruecolor(): Invalid image dimensions in /home/user/public_html/common/vendor/samayo/bulletproof/src/utils/func.image-resize.php on line 58

Warning: imagealphablending() expects parameter 1 to be resource, boolean given in /home/user/public_html/common/vendor/samayo/bulletproof/src/utils/func.image-resize.php on line 59

Warning: imagesavealpha() expects parameter 1 to be resource, boolean given in /home/user/public_html/common/vendor/samayo/bulletproof/src/utils/func.image-resize.php on line 60

Warning: imagecopyresampled() expects parameter 1 to be resource, boolean given in /home/user/public_html/common/vendor/samayo/bulletproof/src/utils/func.image-resize.php on line 72

Warning: imagejpeg() expects parameter 1 to be resource, boolean given in /home/user/public_html/common/vendor/samayo/bulletproof/src/utils/func.image-resize.php on line 77
```

So I had to remove `vendor/samayo/bulletproof/src/utils/func.image-resize.php` and all the code related to it, now everything works

**Comment by elieobeid7** [comment]
reinstalled the library, everything worked, but still this is falty

  /*    if ($files['size'] < $minSize || $files['size'] > $maxSize) {
            $min = intval($minSize / 1000) ?: 1;
            $max = intval($maxSize / 1000) ?: 1;
            $image->error = "Image size should be at least " . $min . " KB, and no more than " . $max . " KB";
            return null;
        }*/

I just commented it out and everything is working great
