### ISSUE TITLE
Cant access the folder

### ISSUE THREAD

**Issue by KuebelElch15** [samayo/bulletproof#85]
Hello, 
Im very new to this script. I´ve made it like the readme, created the form and included the PHP like there.
I`ve created a new folder and named it "bulletproof": Afer I tried 1 upload, I cant access to the folder. Cant open it, cant delete it and cant download it. Im allways getting the response "550 Can't change directory to bulletproof: Permission denied". How can I delete the folder or access it?

**Comment by twistedpixel** [comment]
It’s probably a permissions problem with the apache user/group. If you open a terminal and “ls -la” within the directory you uploaded the file to, what is the output? Also “ls -la ../“ from same directory to check the parent directory permissions.

What OS are you using?

**Comment by KuebelElch15** [comment]
I'm simply running a ovh webserver. I Don't have a terminal...
(https://www.ovh.de/hosting/performance-hosting.xml)

Its php 7.0, the Server I dont know

**Comment by twistedpixel** [comment]
Hard to debug without a terminal but generally these systems are set up with reasonable permissions by default.

Probably your best bet is to test creating folders with mkdir() and removing them again with unlink(). If that works fine, then your code/confit is bad (perhaps an incorrect path?) If that doesn’t work, you’ll need to contact your host’s support people as you won’t be able to change permissions without a terminal - or some web-based control panel. Even then, you’ll need to find out what user the web server runs as and which groups it is in so maybe contacting support is best.

**Comment by samayo** [comment]
Yes what @twistedpixel  said. It's most likely a permission issue, check your directory permssion and let me know
