### ISSUE TITLE
Unable to set the location of the file

### ISSUE THREAD

**Issue by MobElian** [samayo/bulletproof#86]
# Unable to set the location of the file
I'm using BulletProof for my web app and when I try to set the location of the file, it's not working.

This is my code:
```php
public function add(): void {
        $uploader = new Image($_FILES);
        $uploader
            ->setName(Keygen::alphanum()->generate())
            ->setMime(["png"])
            ->setLocation(BASE_URL . "src/assets/projects");
        if ($uploader["upload"]) {
            try {
                if ($uploader->getMime() !== "png") {
                    throw new \Exception("Image should be png type");
                }
                if($uploader->upload()) {
                    echo $uploader->getName();
                } else {
                    throw new \Exception($uploader["error"]);
                }
            } catch (\Exception $e) {
                die($e->getMessage());
            }
        }
    }
```
I have and error too:

> Warning: move_uploaded_file(bulletproof/xf38pLf5nYYPgr37.png): failed to open stream: Permission denied in /Applications/MAMP/htdocs/adrien-website/vendor/samayo/bulletproof/src/bulletproof.php on line 480

> Warning: move_uploaded_file(): Unable to move 'path_to/tmp/php/phpLotXnT' to 'bulletproof/xf38pLf5nYYPgr37.png' in path_to/vendor/samayo/bulletproof/src/bulletproof.php on line 480

My PHP version is: 7.2.1

Thanks for your help :)

**Comment by MobElian** [comment]
Ok, I resolve this problem by just changing the permissions to read and write.

**Comment by samayo** [comment]
Yeah I knew it was a permission issue. Glad you got it fixed
