### ISSUE TITLE
Using on a shared host

### ISSUE THREAD

**Issue by bevan77** [samayo/bulletproof#87]
Hi

I am trying to use this on a shared host but I don't have root access to set file permissions. Is there a way around this?

**Comment by twistedpixel** [comment]
You can try contacting your host. Do you not have ssh access via a chrooted environment? That’s how I usually set up my shared hosting for customers. You can then set permissions that way by logging in as the file owner.

**Comment by samayo** [comment]
Yes, twistedpixed said. In addition, if your problem is setting file permissions and you are able to create a file with the default 755 then pass that as the second argument to your `$image->setLocation(..., 755);` and see what happens.

**Comment by the-javapocalypse** [comment]
moveUploadedFile() keeps on returning False on host. I've updated $tmp_name and $destination to point at right directories. Any help will be appreciated

**Comment by samayo** [comment]
Well, there has to be a reason its not working. Can you give us your code sample?

**Comment by twistedpixel** [comment]
As was suggested to OP, check your permissions. If you don’t have shell access, contact your hosting provider.

In most cases, this is a permissions issue. If you are positive your path is correct, check the web server group has write access to the upload directory (the group is usually www/apache/http or something, and is most likely the group owner of all your web directories/files).

**Comment by samayo** [comment]
glad it worked for you, but please do no alter the class to do something which is already available via the api. Just pass the filename as shown in the readme :)
