### ISSUE TITLE
multilingual bulletproof

### ISSUE THREAD

**Issue by fmkoc** [samayo/bulletproof#92]
hello,
I just started to use bulletproof for my website and modified a little bit to add different language support. and I think that it would be great if multilingual support is added with project's originality

regards

**Comment by samayo** [comment]
Yeah, I've been thinking about this, but currently I don't know which way is best to implement multiple-language support while keeping the simplicity intact. How did you do it? Do you have a fork with examples? I like to see one 👍

**Comment by fmkoc** [comment]
I think the best way to do it is creating predefined error arrays. 

For example I added these to class.
`protected $language;`

```
public function setLanguage($lang)
{
      $this->language = $lang;

      return $this;
}
```
and changed the array as follows
```
protected $commonUploadErrors = array(
     "tr" => array(
           ...
     ),
     "en" => array(
           ...
     )
);
```
and edited the line as follows
```
// check for common upload errors
if (isset($this->_files['error'])) {
        $this->error = $this->commonUploadErrors[$this->language][$this->_files['error']];
}
```

ps. for other errors, I used a temporary (not so useful) method. 

what if it is wanted to done, all errors must be in one array for simplicity.

**Comment by fmkoc** [comment]
I forked the project,
https://github.com/fmkoc/bulletproof/

can be pulled after a quick check.

**Comment by samayo** [comment]
Thanks. Can you send a PR so I can quickly check?
