### ISSUE TITLE
Image stretched when upsizing enabled

### ISSUE THREAD

**Issue by LorincJuraj** [samayo/bulletproof#95]
In some cases image might get stretched. Here is how to reproduce the issue.
I have portrait image which is 1280px wide and 1920 high. I want to resize image to 2000px by 2000px with upsizing enabled (which is by default). The result image will be 1280px by 2000px (stretched).

**Comment by samayo** [comment]
Thanks for the issue and PR. I was going to merge it but you said "In some cases image.." this means I have to check and test it myself as I don't know why it would randomly do that. I will check/test your PR and merge it 👍

**Comment by LorincJuraj** [comment]
I probably wasn't very clear. It's not randomly. It is when image size is smaller than thumbnail size, so every time when upsizing is used.

**Comment by samayo** [comment]
Ok, I took a quick look, I will merge it now and take a better look later 👍
